### ISSUE TITLE
Using tf-ncl with Nomad

### ISSUE THREAD

**Issue by suimong** [tweag/tf-ncl#64]
This is likely a silly question, but I'm trying to migrate to Hashicorp Nomad for workload orchestration at workplace, and since a great many of my workplace environment's configurations have been done in Nickel, this should be no exception. However I'm not super familiar with HCL, and it looks like there are differences between HCL written for Terraform and those for Nomad. Is there any guidance on using or adapting this project to configuring Nomad?

**Comment by vkleen** [comment]
If Nomad is using the same libraries to process as HCL as Terraform is, it should seamlessly accept JSON exported by Nickel. In my view, the interesting part of `tf-ncl` is the ability to automatically generate contracts for the configuration schema expected by Terraform providers. Unfortunately, I have very little experience with Nomad and I don't know if there's a way to extract a machine readable schema from it.

If (and that's a big if) there is a way to get a machine readable schema from Nomad that is reasonably similar to the schemas produced by Terraform, then it shouldn't be too hard to adapt `tf-ncl` to it. Otherwise you should still be able to manually write contracts for it and use Nickel to produce JSON for consumption by Nomad.

**Comment by suimong** [comment]
Thanks for the advice @vkleen. I'll play around and report back.
